# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 진유의 코딩 창고
email: oohh17@naver.com

#write html inside the double quotes to display in jumbotron
description: "<h3>코딩 창고</h3><h1>기록하자.</h1>"



baseurl: "" # the subpath of your site, e.g. /blog
url: "http://firesky11.github.io" # the base hostname & protocol for your site

github_username:  firesky11

# Build settings
markdown: kramdown
